updates:
  -
    directory: /
    package-ecosystem: cargo
    schedule:
      interval: daily
  -
    directory: /
    package-ecosystem: github-actions
    schedule:
      interval: daily
version: 2
