version: 1.0.{build}
image: Visual Studio 2017
platform: x64
configuration: Debug

environment:
  solution_name: c:\\projects\\wolf-engine\\engine\\builds\\mvsc\\wolf.engine.vulkan.Win32.sln
  matrix:
    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.14"
      PYTHON_ARCH: "64"
matrix:
  fast_finish: true
  exclude:
    - platform: x86
      configuration: Debug
    - platform: x86
      configuration: Release
    - platform: x64
      configuration: Release

install:
    # python requirements needed to unpack deps
    - cmd: ./install.cmd
init:
    - "%PYTHON%\\python.exe --version"
build:
  verbosity: minimal
  project: "%solution_name%"
  
skip_commits:
  files:
    - content/*
    - docs/*
    - samples/*
    - utilities/*
    - .gitattributes
    - .gitignore
    - .travis.yml
    - install.sh
    - Logo.jpg
    - /**/*.md

