# https://rust-lang.github.io/rust-clippy/master/

# allowed-scripts
# array-size-threshold
# avoid-breaking-exported-api
# blacklisted-names
# cargo-ignore-publish
# cognitive-complexity-threshold
# cyclomatic-complexity-threshold
# disallowed-methods
# disallowed-types
# doc-valid-idents
# enforced-import-renames
# enum-variant-name-threshold
# enum-variant-size-threshold
# literal-representation-threshold
# max-fn-params-bools
# max-struct-bools
# max-trait-bounds
# msrv
# pass-by-value-size-limit
# single-char-binding-names-threshold
# standard-macro-braces
# third-party
# too-large-for-stack
# too-many-arguments-threshold
# too-many-lines-threshold
# trivial-copy-size-limit
# type-complexity-threshold
# unreadable-literal-lint-fractions
# upper-case-acronyms-aggressive
# vec-box-size-threshold
# verbose-bit-mask-threshold
# warn-on-all-wildcard-imports
