[package]
categories = ["game-development", "game-engines", "games", "graphics", "multimedia", "wasm", "concurrency"]
description = "Wolf is a set of modules for realtime rendering, realtime streaming and game developing"
edition = "2021"
keywords = ["gamedev", "system", "gamedev", "render", "wasm", "web", "worker"]
license = "Apache-2.0"
name = "wolf-demo"
readme = "README.md"
repository = "https://github.com/WolfEngine/WolfEngine/"
version = "3.0.3"

[lib] # remove this for native local debugging
name = "wolf_demo"
path = "src/main.rs"
crate-type = ["cdylib"]

[[bin]]
name = "wolf_demo"
path = "src/main.rs"

[dependencies]
anyhow = {version = "1.0.56", default-features = false}

[target.'cfg(target_arch = "wasm32")'.dependencies]
serde = { version = "1.0.136", default-features = false, features = ["derive"] }
serde_closure = { version = "0.3.2", default-features = false }
wasm-bindgen = { version = "0.2.79", default-features = false }
wasm-mt = {version = "0.1.2", default-features = false }
web-sys = {version = "0.3.56", default-features = false, features = ['console'] }
wolfengine = { path = "../wolf", version = "3.0.2", default-features = false, features= ["system", "wasm"]}

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = {version = "1.17.0", default-features = false, features= ["rt-multi-thread"]}
wolfengine = { path = "../wolf", version = "3.0.2", default-features = false, features= ["system"]}
