env:
  CARGO_TERM_COLOR: always
jobs:
  audit:
    container:
      image: docker://rust:1.57.0-bullseye
    name: Cargo Audit
    needs:
      - clippy
      - conventional-commits-linter
      - fmt-check
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      -
        name: Check Out
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
      -
        name: Cache
        uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed
        with:
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          restore-keys: |
            ${{ runner.os }}-cargo-
      -
        name: Add OS Dependency
        run: make add-os-dependency
        shell: bash
      -
        # TODO: Remove this once the `audit` job is stable.
        continue-on-error: true
        id: audit
        name: Audit
        run: make audit
        shell: bash
    timeout-minutes: 30
  check:
    container:
      image: docker://rust:1.57.0-bullseye
    name: Cargo Check
    needs:
      - clippy
      - conventional-commits-linter
      - fmt-check
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      -
        name: Check Out
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
      -
        name: Cache
        uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed
        with:
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          restore-keys: |
            ${{ runner.os }}-cargo-
      -
        name: Add OS Dependency
        run: make add-os-dependency
        shell: bash
      -
        name: Check
        run: make check
        shell: bash
    timeout-minutes: 30
  conventional-commits-linter:
    container:
      image: docker://rust:1.57.0-bullseye
    name: Conventional Commits Linter
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      -
        name: Check Out
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
      -
        name: Cache
        uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed
        with:
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          restore-keys: |
            ${{ runner.os }}-cargo-
      -
        name: Conventional Commits
        run: ./script/conventional-commits-linter.sh ${{ github.event.pull_request.head.ref }}
        shell: bash
    timeout-minutes: 30
  deny-check:
    container:
      image: docker://rust:1.57.0-bullseye
    continue-on-error: ${{ matrix.checks == 'advisories' }}
    name: Cargo Deny Check
    needs:
      - clippy
      - conventional-commits-linter
      - fmt-check
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      -
        name: Check Out
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
      -
        name: Cache
        uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed
        with:
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          restore-keys: |
            ${{ runner.os }}-cargo-
      -
        name: Add OS Dependency
        run: make add-os-dependency
        shell: bash
      -
        # TODO: Remove this once the `deny-check` job is stable.
        continue-on-error: true
        env:
          DENY_CHECK_WHICH: ${{ matrix.checks }}
        id: deny-check
        name: Deny Check
        run: make deny-check
        shell: bash
      # -
      #   name: Deny Check
      #   uses: EmbarkStudios/cargo-deny-action@0ca727bbae7b7b578b9a5f98186caac35aa2a00d
      #   with:
      #     arguments: |-
      #       --all-features
      #       --workspace
      #     command: check ${{ matrix.checks }}
    strategy:
      matrix:
        checks:
          - advisories
          - bans licenses sources
    timeout-minutes: 30
  clippy:
    container:
      image: docker://rust:1.57.0-bullseye
    name: Cargo Clippy
    needs:
      - conventional-commits-linter
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      -
        name: Check Out
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
      -
        name: Cache
        uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed
        with:
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          restore-keys: |
            ${{ runner.os }}-cargo-
      -
        name: Add OS Dependency
        run: make add-os-dependency
        shell: bash
      -
        name: Clippy
        run: make clippy
        shell: bash
    timeout-minutes: 30
  coverage:
    container:
      image: docker://rust:1.57.0-bullseye
    name: Coverage
    needs:
      - clippy
      - conventional-commits-linter
      - fmt-check
      - test
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      -
        name: Check Out
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
      -
        name: Cache
        uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed
        with:
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          restore-keys: |
            ${{ runner.os }}-cargo-
      -
        name: Add OS Dependency
        run: make add-os-dependency
        shell: bash
      -
        env:
          PACKAGE: ${{ matrix.package }}
          # TARGET: ${{ matrix.target }}
        name: Coverage
        run: make coverage
        shell: bash
      -
        name: Coveralls
        uses: coverallsapp/github-action@9ba913c152ae4be1327bfb9085dc806cedb44057
        with:
          flag-name: ${{ matrix.package }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
    strategy:
      matrix:
        package:
          # - wolf_render
          # - wolf_stream
          - wolf_system
    timeout-minutes: 20
  coverage-finished:
    needs:
      - clippy
      - coverage
      - conventional-commits-linter
      - fmt-check
      - test
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@9ba913c152ae4be1327bfb9085dc806cedb44057
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true
    timeout-minutes: 30
  fmt-check:
    container:
      image: docker://rust:1.57.0-bullseye
    name: Cargo Format Check
    needs:
      - conventional-commits-linter
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      -
        name: Check Out
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
      -
        name: Cache
        uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed
        with:
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          restore-keys: |
            ${{ runner.os }}-cargo-
      -
        name: Add OS Dependency
        run: make add-os-dependency
        shell: bash
      -
        name: Format Check
        run: make fmt-check
        shell: bash
    timeout-minutes: 30
  test:
    container:
      image: docker://rust:1.57.0-bullseye
    name: Cargo Test
    needs:
      - clippy
      - conventional-commits-linter
      - fmt-check
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      -
        name: Check Out
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
      -
        name: Cache
        uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed
        with:
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          restore-keys: |
            ${{ runner.os }}-cargo-
      -
        name: Add OS Dependency
        run: make add-os-dependency
        shell: bash
      -
        env:
          PACKAGE: ${{ matrix.package }}
          # TARGET: ${{ matrix.target }}
        name: Test
        run: make test
        shell: bash
    strategy:
      matrix:
        package:
          # - wolf_render
          # - wolf_stream
          - wolf_system
    timeout-minutes: 30
name: Pull Request Main
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
