env:
  BASE_DIGEST: sha256:bca3c203cdb36f5914ab8568e4c25165643ea9b711b41a8a58b42c80a51ed609
  BASE_NAME: gcr.io/distroless/static-debian11
  BASE_TAG: nonroot
  CARGO_TERM_COLOR: always
jobs:
  build-and-push-docker-image:
    name: Build and Publish Docker Image
    permissions:
      contents: read
      issues: write
      packages: write
      security-events: write
    runs-on: ubuntu-latest
    steps:
      -
        name: Check Out
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      -
        id: release-tag-meta
        name: Release Tag Meta
        uses: ./.github/actions/release-tag-meta
        with:
          git-ref: ${{ github.ref }}
      -
        id: release-package-meta
        name: Release Package Meta
        uses: ./.github/actions/release-package-meta
        with:
          package: ${{ matrix.package }}
      -
        name: Extract Metadata (Tags, Labels) for Docker
        id: metadata
        uses: docker/metadata-action@e5622373a38e60fb6d795a4421e56882f2d7a681
        with:
          labels: |
            org.opencontainers.image.authors=${{ github.actor }}
            org.opencontainers.image.base.digest=${{ env.BASE_DIGEST }}
            org.opencontainers.image.base.name=${{ env.BASE_NAME }}:${{ env.BASE_TAG }}
            org.opencontainers.image.created=1970-01-01T00:00:00Z
            org.opencontainers.image.description=${{ steps.release-package-meta.outputs.package }}
            org.opencontainers.image.documentation=${{ github.server_url }}/${{ github.repository }}/tree/${{ steps.release-tag-meta.outputs.tag }}
            org.opencontainers.image.licenses=MIT
            org.opencontainers.image.ref.name=${{ env.BASE_NAME }}:${{ env.BASE_TAG }}@${{ env.BASE_DIGEST }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}/tree/${{ steps.release-tag-meta.outputs.tag }}
            org.opencontainers.image.title=${{ steps.release-package-meta.outputs.package }}
            org.opencontainers.image.url=${{ github.server_url }}/${{ github.repository }}/tree/${{ steps.release-tag-meta.outputs.tag }}
            org.opencontainers.image.vendor=${{ github.actor }}
            org.opencontainers.image.version=${{ steps.release-tag-meta.outputs.version }}
          images: |
            ghcr.io/${{ github.repository }}/${{ steps.release-package-meta.outputs.package }}
          tags: |
            type=semver,pattern={{version}}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@27d0a4f181a40b142cce983c5393082c365d1480
        with:
          platforms: arm,arm64
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@94ab11c41e45d028884a99163086648e898eed25
        with:
          config: ./.github/buildkitd.toml
          # driver-opts: |
          #   image=moby/buildkit:rootless
      -
        name: Cache Docker Layers
        uses: actions/cache@c3f1317a9e7b1ef106c153ac8c0f00fed3ddbc0d
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: Log in to Docker Hub
        uses: docker/login-action@42d299face0c5c43a0487c477f595ac9cf22f1a7
        with:
          password: ${{ secrets.PACKAGE_REGISTRY }}
          registry: ghcr.io
          username: ${{ github.actor }}
      -
        name: Build and Load Docker Image
        uses: docker/build-push-action@a66e35b9cbcf4ad0ea91ffcaf7bbad63ad9e0229
        with:
          build-args: |
            PACKAGE=${{ matrix.package }}
            REF_NAME=${{ fromJSON(steps.metadata.outputs.json).labels['org.opencontainers.image.ref.name'] }}
            VERSION=${{ fromJSON(steps.metadata.outputs.json).labels['org.opencontainers.image.version'] }}
          cache-from: |
            type=local,src=/tmp/.buildx-cache
          cache-to: |
            type=local,dest=/tmp/.buildx-cache-new,mode=max
          context: .
          labels: |
            ${{ steps.metadata.outputs.labels }}
          load: true
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.PACKAGE_REGISTRY }}
          tags: |
            ${{ steps.metadata.outputs.tags }}
      -
        env:
          TRIVY_PASSWORD: ${{ secrets.PACKAGE_REGISTRY }}
          TRIVY_USERNAME: ${{ inputs.TRIVY_USERNAME }}
        name: Aqua Security Trivy
        uses: aquasecurity/trivy-action@8f4c7160b470bafe4299efdc1c8a1fb495f8325a
        with:
          exit-code: 1
          format: template
          hide-progress: false
          image-ref: ghcr.io/${{ github.repository }}/${{ steps.release-package-meta.outputs.package }}:latest
          output: trivy.sarif
          template: "@/contrib/sarif.tpl"
      -
        name: Upload Sarif
        uses: github/codeql-action/upload-sarif@5f532563584d71fdef14ee64d17bafb34f751ce5
        with:
          category: Aqua Security Trivy
          sarif_file: trivy.sarif
          wait-for-processing: true
      -
        id: anchore
        name: Anchore Scan
        uses: anchore/scan-action@54980bbdae434b8e7903cfcffa98a2601c207962
        with:
          debug: true
          image: ghcr.io/${{ github.repository }}/${{ steps.release-package-meta.outputs.package }}:latest
          severity-cutoff: negligible
      -
        name: Upload Sarif
        uses: github/codeql-action/upload-sarif@5f532563584d71fdef14ee64d17bafb34f751ce5
        with:
          category: Anchore Scan
          sarif_file: ${{ steps.anchore.outputs.sarif }}
          wait-for-processing: true
      -
        name: Build and Push Docker Image
        uses: docker/build-push-action@a66e35b9cbcf4ad0ea91ffcaf7bbad63ad9e0229
        with:
          build-args: |
            PACKAGE=${{ matrix.package }}
            REF_NAME=${{ fromJSON(steps.metadata.outputs.json).labels['org.opencontainers.image.ref.name'] }}
            VERSION=${{ fromJSON(steps.metadata.outputs.json).labels['org.opencontainers.image.version'] }}
          cache-from: |
            type=local,src=/tmp/.buildx-cache
          cache-to: |
            type=local,dest=/tmp/.buildx-cache-new,mode=max
          context: .
          labels: |
            ${{ steps.metadata.outputs.labels }}
          platforms: |
            linux/amd64
            linux/arm/v7
            linux/arm64
          push: true
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.PACKAGE_REGISTRY }}
          tags: |
            ${{ steps.metadata.outputs.tags }}
      -
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move Cache
        run: |
          rm -fr /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
    strategy:
      matrix:
        package:
          - wolf
    timeout-minutes: 30
name: Release Published
on:
  release:
    types:
      - published
